version: '3'
services:
  ms:
    image: "desafio"
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_SERVER: db
      DB_PORT: 3306
      DB_DATABASE: exchanges
      DB_USER: root
      DB_PASSWORD: secret
    depends_on:
      - db      
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: exchanges